- alias: "Schichtstatistik: Tägliche Synchronisation"
id: schichtstatistik_daily_update
trigger:
- platform: time
at: "03:00:00"
- platform: homeassistant
event: start
action:
- action: script.schichtstatistik_aktualisieren
